Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,9 +39,17 @@ jobs:
         run: |
           cd infra/
           sudo apt-get install -y jq
-          terraform output -json instance_ips | jq -r '.[]' > instance_ips.txt
-          terraform output -raw private_key > k8s-key.pem
-          chmod 600 k8s-key.pem
+          if terraform output -json instance_ips > tmp.json; then
+            jq -r '.[]' tmp.json > instance_ips.txt
+          else
+            echo "Failed to extract instance IPs" && exit 1
+          fi
+          if terraform output -raw private_key > k8s-key.pem; then
+            chmod 600 k8s-key.pem
+          else
+            echo "Failed to extract private key" && exit 1
+          fi
+          echo "Extracted IPs:"
           cat instance_ips.txt
 
       - name: Upload SSH Key & IPs as Artifacts
